I'm using the June 2025 Digital City Map from [here](https://www.nyc.gov/content/planning/pages/resources/datasets/digital-city-map)

In [32]:
import geopandas as gpd
import matplotlib.pyplot as plt

# Read the shapefile
df = gpd.read_file('data/DCM_StreetCenterLine.shp')
df.head()

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry
0,Staten Island,Mapped_St,City_St,Ellis Street,None,None,90,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,119.470635,"LINESTRING Z (914472.428 126532.336 0, 914371...."
1,Staten Island,Mapped_St,City_St,Bamberger Lane,None,None,50,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,525.598640,"LINESTRING Z (937763.891 136995.709 0, 937846...."
2,Bronx,Mapped_St,City_St,Nereid Avenue,None,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1865.001879,"MULTILINESTRING Z ((1023332.375 267253.299 0, ..."
3,Bronx,Mapped_St,City_St,Split Rock Road,None,None,50,Gen_use,Walkway,Improved,N,N,N,N,N,NaT,138.833987,"LINESTRING Z (1035784.873 263086.754 0, 103575..."
4,Bronx,Mapped_St,City_St,East 178 Street,None,None,30,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,426.849470,"LINESTRING Z (1017254.68 245892.932 0, 1017625..."

In [33]:
df = df[df['Feat_statu']=="City_St"]

In [37]:
df['Street_NM'] = df['Street_NM'].str.lower()
df['words_count'] = df['Street_NM'].str.count(" ")
df.sort_values('words_count', ascending=True).head(50)

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry,words_count
15184,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,165.495554,"LINESTRING Z (1004233.096 254526.038 0, 100436...",0
14756,Manhattan,Mapped_St,City_St,broadway,None,None,76.1-76.5,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,118.156790,"LINESTRING Z (981134.585 197336.253 0, 981149....",0
11481,Manhattan,Mapped_St,City_St,broadway,None,None,>80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,197.927286,"MULTILINESTRING Z ((987582.221 212336.589 0, 9...",0
2649,Manhattan,Mapped_St,City_St,broadway,None,None,74.7-81.8,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,384.211481,"LINESTRING Z (980575.254 196444.42 0, 980777.5...",0
40494,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,159.957225,"LINESTRING Z (1004075.78 191823.501 0, 1004204...",0
40493,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,46.654708,"LINESTRING Z (1004038.017 191850.899 0, 100407...",0
40492,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,371.074621,"LINESTRING Z (1003744.101 192077.415 0, 100403...",0
40491,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,278.657033,"LINESTRING Z (1003519.479 192242.323 0, 100374...",0
40490,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,218.723098,"LINESTRING Z (1003343.649 192372.415 0, 100351...",0
5963,Bronx,Mapped_St,City_St,broadway,None,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,2156.939536,"MULTILINESTRING Z ((1011122.137 260515.006 0, ...",0
45515,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,4.496727,"LINESTRING Z (999149.223 195481.642 0, 999152....",0
13090,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,290.576137,"LINESTRING Z (1007515.366 256197.787 0, 100772...",0
45514,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,272.676750,"LINESTRING Z (998930.643 195644.662 0, 999149....",0
3199,Manhattan,Mapped_St,City_St,broadway,None,None,150,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1279.028104,"MULTILINESTRING Z ((993165.739 231543.183 0, 9...",0
45512,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,481.982976,"LINESTRING Z (998320.037 196093.148 0, 998483....",0
8076,Manhattan,Mapped_St,City_St,broadway,None,None,52,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,154.893666,"LINESTRING Z (980575.254 196444.42 0, 980565.2...",0
45511,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,75.112282,"LINESTRING Z (998259.755 196137.958 0, 998320....",0
45510,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,146.781116,"LINESTRING Z (998142.755 196226.576 0, 998157....",0
45509,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,108.276886,"LINESTRING Z (998058.34 196294.384 0, 998142.7...",0
45508,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,14.276885,"LINESTRING Z (998047.21 196303.325 0, 998058.3...",0
677,Manhattan,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,551.893547,"MULTILINESTRING Z ((987449.603 211352.07 0, 98...",0
8606,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1424.838379,"MULTILINESTRING Z ((1005516.742 255164.154 0, ...",0
298,Manhattan,Mapped_St,City_St,broadway,None,None,79,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,218.881938,"LINESTRING Z (981736.192 198279.428 0, 981865....",0
45513,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,275.632490,"LINESTRING Z (998708.284 195807.542 0, 998930....",0
7777,Bronx,Mapped_St,City_St,esplanade,None,None,140,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,950.842999,"MULTILINESTRING Z ((1024491.095 252542.547 0, ...",0
15648,Manhattan,Mapped_St,City_St,bowery,None,None,Unknown but >90,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,481.720324,"LINESTRING Z (985136.205 199783.908 0, 985296....",0
10158,Manhattan,Mapped_St,City_St,bowery,None,None,>100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,174.007888,"MULTILINESTRING Z ((985053.414 199635.95 0, 98...",0
50673,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,255.313135,"LINESTRING Z (994470.553 198025.014 0, 994704....",0
8650,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,143.591697,"LINESTRING Z (1007407.802 256102.663 0, 100751...",0
16252,Manhattan,Mapped_St,City_St,broadway,None,None,77,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,92.528673,"MULTILINESTRING Z ((981241.193 197507.972 0, 9...",0
52513,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,130.308258,"LINESTRING Z (1001889.121 193442.927 0, 100199...",0
52514,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,265.717765,"LINESTRING Z (1001994.777 193366.658 0, 100221...",0
15435,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,862.322660,"LINESTRING Z (1003628.983 253535.587 0, 100361...",0
9935,Manhattan,Mapped_St,City_St,broadway,None,None,150,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1589.932657,"MULTILINESTRING Z ((991420.526 227632.104 0, 9...",0
52515,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,149.076881,"LINESTRING Z (1002212.329 193214.089 0, 100233...",0
52516,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,229.747264,"LINESTRING Z (1002330.426 193123.112 0, 100251...",0
11507,Manhattan,Mapped_St,City_St,bowery,Joey Ramone Place,None,120,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,277.380425,"MULTILINESTRING Z ((986447.283 203636.761 0, 9...",0
8629,Manhattan,Mapped_St,City_St,broadway,Juan Rodriguez Way,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,562.681077,"MULTILINESTRING Z ((1001215.753 247299.629 0, ...",0
52517,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,105.908308,"LINESTRING Z (1002514.382 192985.474 0, 100259...",0
52519,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,35.404133,"LINESTRING Z (1002796.091 192779.011 0, 100282...",0
7799,Manhattan,Mapped_St,City_St,broadway,None,None,Unknown,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,235.148620,"MULTILINESTRING Z ((982619.681 199656.041 0, 9...",0
52520,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,226.151467,"LINESTRING Z (1002824.355 192757.691 0, 100300...",0
52521,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,150.265254,"LINESTRING Z (1003004.899 192621.499 0, 100312...",0
12386,Manhattan,Mapped_St,City_St,broadway,None,None,150,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,10593.418130,"MULTILINESTRING Z ((999242.063 242680.836 0, 9...",0
52522,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,53.252093,"LINESTRING Z (1003126.192 192532.798 0, 100316...",0
3219,Manhattan,Mapped_St,City_St,broadway,None,None,>80,Mjr_st,Walkway,Improved,N,N,N,N,N,NaT,106.509287,"LINESTRING Z (987564.367 212166.16 0, 987575.4...",0
52523,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,124.230069,"LINESTRING Z (1003169.158 192501.338 0, 100325...",0
6615,Bronx,Mapped_St,City_St,broadway,None,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,570.400022,"MULTILINESTRING Z ((1011926.921 262291.352 0, ...",0
12158,Manhattan,Mapped_St,City_St,broadway,None,None,102,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,226.310707,"LINESTRING Z (982124.847 198871.45 0, 982247.1...",0
52518,Brooklyn,Mapped_St,City_St,broadway,None,None,80,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,243.364056,"LINESTRING Z (1002599.228 192922.088 0, 100279...",0